training_params:
  max_epochs: 30
  auto_lr_find: false
  gpus: 1
model_params:
  model_type: conv-vae # vae or conv-vae
  lr: 0.005
  batch_size: 1
  hidden_size: 4096
  latent_size: 128
  alpha: 1024
  dataset: "celeba"
  save_images: true
  save_path: "log_images/"
  channels: 3
  height: 64
  width: 64
logger_params:
  name: "conv-vae"
  save_dir: "logs/"