train:
  BATCH_SIZE: 128
  EPOCHS: 20
  LOG_INTERVAL: 100
  Z_DIM: 2
  LEARNING_RATE: 0.001
  PRR: True
  Z1_RANGE: 2
  Z2_RANGE: 2
  Z1_INTERVAL: 0.2
  Z2_INTERVAL: 0.2
  checkpoint:
      enabled: true
      upload_enabled: false
      resume_file: ""
  results_dir: "results"
  export_dir: ""
test:
  checkpoint:
      enabled: true
      upload_enabled: false
      resume_file: ""
  export_dir: ""
preprocess:
  vendor: "unity"